  [[main]]
  name = "मुख्य पृष्ठ"
  identifier = "main"
  weight = 100
  url = "/hi/"

  [[main]]
  name = "लेख सूची"
  weight = 200
  identifier = "लेख"
  url = "/hi/post/"

  [[main]]
  name = "मोबाईल ऐप"
  weight = 300
  identifier = "मोबाईल ऐप"
  url = "/hi/vinayak-hora-astrology-app/"



  #[[main]]
  #name = "संपर्क विधि"
  #weight = 400
  #identifier = "contact"
  #url = "/hi/contact/"

  [[main]]
  name = "मेरे बारे में"
  weight = 700
  identifier = "about-me"
  url = "/hi/about-me/"


  [[footer]]
  name = "गोपनीयता नीति"
  weight = 1
  identifier = "policy"
  url = "/hi/policy/"

  [[footer]]
  name = "उपयोग की शर्तें"
  weight = 2
  identifier = "terms-of-use"
  url = "/hi/terms-of-use/"