  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

   [[main]]
  name = "Mobile App"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact Us"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[main]]
  name = "About Me"
  weight = 700
  identifier = "about-me"
  url = "/about-me/"

  #[[footer]]
  #ame = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"

  [[footer]]
  name = "Privacy Policy"
  weight = 1
  identifier = "policy"
  url = "/policy/"