  [[main]]
  name = "मुख्य पृष्ठ"
  identifier = "main"
  weight = 100
  url = "/hi/"

  [[main]]
  name = "लेख सूची"
  weight = 200
  identifier = "posts"
  url = "/hi/post/"

  [[main]]
  name = "परिचय"
  weight = 300
  identifier = "about"
  url = "/hi/about/"

  [[main]]
  name = "संपर्क विधि"
  weight = 400
  identifier = "contact"
  url = "/hi/contact/"

  [[footer]]
  name = "गोपनीयता नीति"
  weight = 1
  identifier = "policy"
  url = "/hi/policy/"