
title = "Vinayak Hora"
author = "Ram Mohan Kapil"
#copyright = "2020-2021"
description = "Vedic Astrology"
profilePicture = "images/logo.png"
youtubeIcon = "images/yt_icon_red_digital.png"
img = "images/GetItOnGooglePlay_Badge_Web_color.png"
#customText = "<a href='https://play.google.com/store/apps/details?id=com.vinayakhora.vinayak_hora' target='_blank'>https://play.google.com/store/apps/details?id=com.vinayakhora.vinayak_hora</a>"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

# Full link to license
#license = "https://creativecommons.org/licenses/by/4.0/"

# disableTitleCapitalization = true

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

# Sidebar/Content Ratio
contentratio = 0.6

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.
#[[socialIcons]]
#icon = "images/GetItOnGooglePlay_Badge_Web_color_English.png"
#icon = "fab fa-google-play"
#title = "Google Play Store"
#url = "https://play.google.com/store/apps/details?id=com.vinayakhora.vinayak_hora"

#[[socialIcons]]
#icon = "fa-brands fa-youtube"
#title = "GitHub"
#url = "https://github.com/lxndrblz/anatole/"

#[[socialIcons]]
#icon = "fa-brands fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

#[[socialIcons]]
#icon = "fa-solid fa-envelope"
#title = "e-mail"
#url = "mailto:mail@example.com"

[mermaid]
# enable = true